### ISSUE TITLE
Panic error because of Sheet Name

### ISSUE THREAD

**Issue by elric667** [rentziass/territory_wars_report#1]
Welcome to Territory Wars Report
--------------------------------
Please report any issue on https://github.com/rentziass/territory_wars_report
Come say hi on https://discord.gg/YGUa2Fy

Enter your guild swgoh.gg's URL: https://swgoh.gg/g/3510/0otini/
Enter your opponent swgoh.gg's URL: https://swgoh.gg/g/6012/llince-syndicte/
Processed 47/47 toon rosters for 0otini...
Processed 50/50 toon rosters for ∆LLi∆NCE SYNDIC∆TE...
panic: sheet name must be less than 31 characters long.  It is currently '32' characters long

goroutine 1 [running]:
main.writeToXLSX(0xc042070c90, 0xc042070cc0, 0xc042070cf0, 0xc0422340c0, 0xc042588240, 0x0, 0x0)
        /Users/francescorenzi/go/src/github.com/rentziass/territory_wars_report/main.go:204 +0x3081
main.main()
        /Users/francescorenzi/go/src/github.com/rentziass/territory_wars_report/main.go:146 +0x11e9

**Comment by rentziass** [comment]
Oh, had no idea about that limit, will look into it and thanks for reporting!

**Comment by rentziass** [comment]
Addressed in [v0.2.1](https://github.com/rentziass/territory_wars_report/releases/tag/v0.2.1), closing.

**Comment by elric667** [comment]
Thank you for addressing this error.  I figured out why it was caused the Other guild has special characters in their name causing the limit to be hit.
